use_frameworks!

platform :ios, '9.0'

target 'AppsFlyerSDKLessSKAdNetworkClient_Example' do
  pod 'AppsFlyerSDKLessSKAdNetworkClient', :path => '../'

  target 'AppsFlyerSDKLessSKAdNetworkClient_Tests' do
    inherit! :search_paths
    pod 'OHHTTPStubs'
    pod 'OCMock'
  end
  
  target 'AppsFlyerSDKLessSKAdNetworkClient_Example-Swift' do
    pod 'AppsFlyerSDKLessSKAdNetworkClient', :path => '../'
  end
end
