use_frameworks!

platform :ios, '9.0'

target 'AppsFlyerSDKLessSKAdNetworkClient_Example' do
  pod 'AppsFlyerSDKLessSKAdNetworkClient', :path => '../'

  target 'AppsFlyerSDKLessSKAdNetworkClient_Tests' do
    inherit! :search_paths
    pod 'OHHTTPStubs'
    pod 'OCMock'
  end
  
  target 'AppsFlyerSDKLessSKAdNetworkClient_Example-Swift' do
    pod 'AppsFlyerSDKLessSKAdNetworkClient', :path => '../'
  end
end


post_install do |installer|
    installer.generated_projects.each do |project|
          project.targets.each do |target|
              target.build_configurations.each do |config|
                  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
               end
          end
   end
end
